version: "3"
services:
  leakage_analysis:
    build: ./leakage-analysis
    ports:
      - "5000:5000"
    environment:
      - PYTHONUNBUFFERED=1
      - SONAR_FORCEAUTHENTICATION=false
    volumes:
      - ./leakage-analysis/src:/app/leakage-analysis/src
      - ./leakage-analysis/static:/app/leakage-analysis/static
      - ./leakage-analysis/uploads:/var/www/uploads
